# This GitHub action runs your tests for each commit push and/or PR. Optionally
# you can turn it on using a cron schedule for regular testing.
#
name: Acceptance Tests (EU)
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.vscode'
      - '.gitignore'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
  # For systems with an upstream API that could drift unexpectedly (like most SaaS systems, etc.),
  # we recommend testing at a regular interval not necessarily tied to code changes. This will 
  # ensure you are alerted to something breaking due to an API change, even if the code did not
  # change.
  schedule:
    - cron: '0 13 * * *'
jobs:
  # ensure the code builds...
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3.4.0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        cache: true
      id: go
    - uses: actions/cache@v3
      continue-on-error: true
      timeout-minutes: 2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      run: |
        go build -v ./...

  # run acceptance tests in a matrix with Terraform core versions
  test:
    name: Matrix Test
    needs: [build]
    runs-on: ubuntu-latest

    env:
      PINGONE_CLIENT_ID: ${{ secrets.EU_PINGONE_CLIENT_ID }}
      PINGONE_CLIENT_SECRET: ${{ secrets.EU_PINGONE_CLIENT_SECRET }}
      PINGONE_ENVIRONMENT_ID: ${{ secrets.EU_PINGONE_ENVIRONMENT_ID }}
      PINGONE_REGION: Europe

    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3.4.0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        cache: true
      id: go
    - uses: actions/cache@v3
      continue-on-error: true
      timeout-minutes: 2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}

    - name: Get dependencies
      run: |
        go mod download

    - name: Acceptance tests
      timeout-minutes: 10
      run: |
        make testacc
